apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: node-pool
spec:
  template:
    metadata:
      labels:
        billing-team: my-team
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default

      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: "eks.amazonaws.com/instance-family"
          operator: In
          values: ["t4g"]
        - key: "eks.amazonaws.com/instance-size"
          operator: In
          values: ["medium"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-southeast-2"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64", "amd64"]

  limits:
    cpu: "8"
    memory: 32Gi
