---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: all-in-one-cluster
  region: ap-southeast-2
  version: "1.33"

vpc:
  cidr: "10.0.0.0/16"
  nat:
    gateway: Single

managedNodeGroups:
  - name: node-group-medium
    spot: true
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 20
    privateNetworking: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/all-rounder.pub
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
